# Generated by Django 4.2.3 on 2023-08-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0007_reservation_preorderfood'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table_no',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='PreOrderFood',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
