# Generated by Django 4.2.3 on 2023-08-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0010_remove_preorderfood_reserved_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtable',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tables', to='Restaurants.reservation'),
        ),
    ]
