# Generated by Django 4.2.3 on 2023-08-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0011_alter_reservedtable_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='totalAmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedtable',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.reservation'),
        ),
    ]
